name: Build

on:
  push:
    branches:
      - "**"

jobs:
  build:
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 1

      - name: Setup Go env
        uses: actions/setup-go@v3
        with:
          go-version: 1.17

      - name: Download Go modules
        run: go mod download

      - name: Build
        run: make

      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: dist
          path: ./aws-icons.alfredworkflow
